[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
